### ISSUE TITLE
Two game issues Pretty Soldier Sailor Moon (sailormnou) and Tank Force 4 players (tankfrce4)

### ISSUE THREAD

**Issue by Wilstorm** [libretro/fbalpha#189]
Running RetroPie 4.4.9, lr-fbalpha 0.2.97.44 5d60621, RA 1.7.6 and Emulationstation 2.8.2 on a Raspberry Pi 3.

I don't know if this is the correct place as I am getting weird anomalies running sailormnou. It seems to run fine when run from the ```fba``` folder no issues at all but when using the ```arcade``` folder it flakes out. The screen is shifted on the first snap (blue background), it removes the U.S.A. in the disclaimer on the 2nd snap and it starts with free play in the 3rd. None of this happens when run from the ```fba``` folder. 

**Background shifted up:**
![sailormnou-190321-181254](https://user-images.githubusercontent.com/8192258/54791561-66396e80-4c08-11e9-99eb-985fe2809c14.png)

**Background shifted up:**
![sailormnou-190321-233336](https://user-images.githubusercontent.com/8192258/54830268-33ce5680-4c86-11e9-907d-310a9fe2eec5.png)

**U.S.A. missing from disclaimer:**
![sailormnou-190321-181313](https://user-images.githubusercontent.com/8192258/54791568-6afe2280-4c08-11e9-92c1-da4794c72521.png)

**U.S.A. present in disclaimer:**
![sailormnou-190321-233206](https://user-images.githubusercontent.com/8192258/54830345-582a3300-4c86-11e9-9388-ac26161d092c.png)

**Free credits:**
![sailormnou-190321-233835](https://user-images.githubusercontent.com/8192258/54830384-68daa900-4c86-11e9-9383-f9cd3528bb66.png)

**Graphical niggles:**
![sailormnou-190321-182032](https://user-images.githubusercontent.com/8192258/54791570-6f2a4000-4c08-11e9-92cc-c1596604bd34.png)

With tankfrce4 it just exits back to the game selection screen. It was working prior to updating to the current version. Here's the line in the log where it crashes.

```
[INFO] Environ SET_VARIABLES.
[INFO] Saved core options file to "/opt/retropie/configs/all/retroarch-core-options.cfg"
[INFO] Environ GET_VARIABLE fba-dipswitch-tankfrce4-Service_Mode:
[INFO] 	(Default) Off
[libretro INFO] [Cheevos] System RAM set to 0x6e2b580c 104624
/opt/retropie/supplementary/runcommand/runcommand.sh: line 1012: 11266 Aborted                 /opt/retropie/emulators/retroarch/bin/retroarch -L /opt/retropie/libretrocores/lr-fbalpha/fbalpha_libretro.so --config /opt/retropie/configs/arcade/retroarch.cfg "/home/pi/RetroPie/roms/arcade/tankfrce4.zip" --verbose --appendconfig /dev/shm/retroarch.cfg
```

**Comment by dinkc64** [comment]
@barbudreadmon, not sure where these are coming from, but I certainly can't reproduce them on my side.

**Comment by barbudreadmon** [comment]
@Wilstorm my guess is an old eeprom stored in your arcade folder, you might have a fba folder in your arcade folder with files like `tankfrce4.fs` and `sailormnou.nv`, or maybe somewhere else depending on your setup (but i think this path is the right one in retropie), so search thoroughly for those files and delete them. Anyway that's not an emulator issue, that's definitely a setup issue.

**Comment by Wilstorm** [comment]
@barbudreadmon - I was running 0.2.97.43 and upgraded to 0.2.97.44 and that's when things started breaking. I deleted all the *.fs and *.nvram proms and both games are working perfectly now. Thank you kindly.

@dinkc64 - Thanks for taking a look. The two main cores I mainly use are mame2003-plus and FBA but anyway Arcadez speaks highly of you and you have helped him with a getting a few games on the straight and narrow on the plus core. 

I have read many of your posts on other forums. I'm having a heck of a time getting the last few ROMs from the .44 set, even after several months. I just can't find djboy, djboya, kof98pfe, mk2ute, umk3te and that friggin' nitedrvr sample. That thing is elusive. Anyway in time. :)

I will close out this issue. Thanks again for taking a look and have a great weekend fellas!

**Comment by Wilstorm** [comment]
@barbudreadmon - I might have spoke too soon for Tank Force (tankfrce4). If I delete tankfrce4.fs from ```/home/pi/RetroPie/roms/arcade/fba``` I can run the game once. If that file is present it crashes back to the game selection screen. I have to delete tankfrce4.fs every time I want to run the game. Here's the verbose log.

```
Parameters: 
Executing: /opt/retropie/emulators/retroarch/bin/retroarch -L /opt/retropie/libretrocores/lr-fbalpha/fbalpha_libretro.so --config /opt/retropie/configs/fba/retroarch.cfg "/home/pi/RetroPie/roms/fba/tankfrce4.zip" --verbose --appendconfig /dev/shm/retroarch.cfg
[INFO] RetroArch 1.7.6 (Git 9750719)
[INFO] Redirecting save file to "/home/pi/RetroPie/roms/fba/tankfrce4.srm".
[INFO] Redirecting savestate to "/home/pi/RetroPie/roms/fba/tankfrce4.state".
[INFO] === Build =======================================
Capabilities: NEON VFPv3 VFPv4 
Built: Mar  8 2019
[INFO] Version: 1.7.6
[INFO] Git: 9750719
[INFO] =================================================
[INFO] Loading dynamic libretro core from: "/opt/retropie/libretrocores/lr-fbalpha/fbalpha_libretro.so"
[INFO] [overrides] no core-specific overrides found at /home/pi/.config/retroarch/config/FB Alpha/FB Alpha.cfg.
[INFO] [overrides] no content-dir-specific overrides found at /home/pi/.config/retroarch/config/FB Alpha/fba.cfg.
[INFO] [overrides] game-specific overrides found at /home/pi/.config/retroarch/config/FB Alpha/tankfrce4.cfg.
[INFO] Config: appending config "/home/pi/.config/retroarch/config/FB Alpha/tankfrce4.cfg"
[INFO] [recording] twitch streaming key empty
[INFO] Shaders: preset directory: /home/pi/.config/retroarch/shaders/presets
[INFO] Shaders: no game-specific preset found at /home/pi/.config/retroarch/shaders/presets/FB Alpha/tankfrce4.cgp.
[INFO] Shaders: no game-specific preset found at /home/pi/.config/retroarch/shaders/presets/FB Alpha/tankfrce4.glslp.
[INFO] Shaders: no content-dir-specific preset found at /home/pi/.config/retroarch/shaders/presets/FB Alpha/fba.cgp.
[INFO] Shaders: no content-dir-specific preset found at /home/pi/.config/retroarch/shaders/presets/FB Alpha/fba.glslp.
[INFO] Shaders: no core-specific preset found at /home/pi/.config/retroarch/shaders/presets/FB Alpha/FB Alpha.cgp.
[INFO] Shaders: no core-specific preset found at /home/pi/.config/retroarch/shaders/presets/FB Alpha/FB Alpha.glslp.
[INFO] Environ SET_SUBSYSTEM_INFO.
[INFO] Special game type: CBS ColecoVision
[INFO]   Ident: cv
[INFO]   ID: 1
[INFO]   Content:
[INFO]     Rom (required)
[INFO] Special game type: MSX 1
[INFO]   Ident: msx
[INFO]   ID: 4
[INFO]   Content:
[INFO]     Rom (required)
[INFO] Special game type: Nec PC-Engine
[INFO]   Ident: pce
[INFO]   ID: 5
[INFO]   Content:
[INFO]     Rom (required)
[INFO] Special game type: Nec SuperGrafX
[INFO]   Ident: sgx
[INFO]   ID: 7
[INFO]   Content:
[INFO]     Rom (required)
[INFO] Special game type: Nec TurboGrafx-16
[INFO]   Ident: tg16
[INFO]   ID: 9
[INFO]   Content:
[INFO]     Rom (required)
[INFO] Special game type: Sega GameGear
[INFO]   Ident: gg
[INFO]   ID: 2
[INFO]   Content:
[INFO]     Rom (required)
[INFO] Special game type: Sega Master System
[INFO]   Ident: sms
[INFO]   ID: 8
[INFO]   Content:
[INFO]     Rom (required)
[INFO] Special game type: Sega Megadrive
[INFO]   Ident: md
[INFO]   ID: 3
[INFO]   Content:
[INFO]     Rom (required)
[INFO] Special game type: Sega SG-1000
[INFO]   Ident: sg1k
[INFO]   ID: 6
[INFO]   Content:
[INFO]     Rom (required)
[INFO] Special game type: ZX Spectrum
[INFO]   Ident: spec
[INFO]   ID: 10
[INFO]   Content:
[INFO]     Rom (required)
[INFO] Special game type: Neogeo CD
[INFO]   Ident: neocd
[INFO]   ID: 11
[INFO]   Content:
[INFO]     Iso (required)
[INFO] Remaps: remap directory: /opt/retropie/configs/fba/
[INFO] Remaps: no game-specific remap found at /opt/retropie/configs/fba/FB Alpha/tankfrce4.rmp.
[INFO] Remaps: no content-dir-specific remap found at /opt/retropie/configs/fba/FB Alpha/fba.rmp.
[INFO] Remaps: no core-specific remap found at /opt/retropie/configs/fba/FB Alpha/FB Alpha.rmp.
[INFO] Redirecting save file to "/home/pi/RetroPie/roms/fba/tankfrce4.srm".
[INFO] Redirecting savestate to "/home/pi/RetroPie/roms/fba/tankfrce4.state".
[INFO] Environ GET_LOG_INTERFACE.
[INFO] Content loading skipped. Implementation will load it on its own.
[INFO] CRC32: 0xa8ce56db .
[libretro INFO] Setting save dir to /home/pi/RetroPie/roms/fba/
[INFO] Environ SYSTEM_DIRECTORY: "/home/pi/RetroPie/BIOS".
[libretro INFO] Setting system dir to /home/pi/RetroPie/BIOS
[INFO] Environ SET_CONTROLLER_INFO.
[INFO] Controller port: 1
[INFO]    Classic (ID: 5)
[INFO]    Modern (ID: 517)
[INFO]    Mouse (ball only) (ID: 2)
[INFO]    Mouse (full) (ID: 514)
[INFO] Controller port: 2
[INFO]    Classic (ID: 5)
[INFO]    Modern (ID: 517)
[INFO]    Mouse (ball only) (ID: 2)
[INFO]    Mouse (full) (ID: 514)
[INFO] Controller port: 3
[INFO]    Classic (ID: 5)
[INFO]    Modern (ID: 517)
[INFO]    Mouse (ball only) (ID: 2)
[INFO]    Mouse (full) (ID: 514)
[INFO] Controller port: 4
[INFO]    Classic (ID: 5)
[INFO]    Modern (ID: 517)
[INFO]    Mouse (ball only) (ID: 2)
[INFO]    Mouse (full) (ID: 514)
[INFO] Environ SET_VARIABLES.
[INFO] Environ GET_VARIABLE fba-cpu-speed-adjust:
[INFO] 	100
[INFO] Environ GET_VARIABLE fba-aspect:
[INFO] 	DAR
[INFO] Environ GET_VARIABLE fba-allow-depth-32:
[INFO] 	disabled
[INFO] Environ GET_VARIABLE fba-vertical-mode:
[INFO] 	disabled
[INFO] Environ GET_VARIABLE fba-frameskip:
[INFO] 	0
[INFO] Environ GET_VARIABLE fba-hiscores:
[INFO] 	enabled
[INFO] Environ GET_VARIABLE fba-samplerate:
[INFO] 	48000
[INFO] Environ GET_VARIABLE fba-sample-interpolation:
[INFO] 	4-point 3rd order
[INFO] Environ GET_VARIABLE fba-fm-interpolation:
[INFO] 	4-point 3rd order
[INFO] Environ GET_VARIABLE fba-analog-speed:
[INFO] 	10
[INFO] Environ GET_VARIABLE fba-cyclone:
[INFO] 	disabled
[libretro INFO] [FBA] Archive: tankfrce4
[libretro INFO] [FBA] Archive: tankfrce
[libretro ERROR] [FBA] Couldn't locate the tankfrce archive anywhere, this game probably won't boot.
[libretro INFO] [FBA] Using ROM with good CRC and name tf1_snd0.bin from archive /home/pi/RetroPie/roms/fba/tankfrce4
[libretro INFO] [FBA] Using ROM with good CRC and name tf1_prg0.bin from archive /home/pi/RetroPie/roms/fba/tankfrce4
[libretro INFO] [FBA] Using ROM with good CRC and name tf1_prg1.bin from archive /home/pi/RetroPie/roms/fba/tankfrce4
[libretro INFO] [FBA] Using ROM with good CRC and name tfu4prg7.bin from archive /home/pi/RetroPie/roms/fba/tankfrce4
[libretro INFO] [FBA] Using ROM with good CRC and name cus64-64a1.mcu from archive /home/pi/RetroPie/roms/fba/tankfrce4
[libretro INFO] [FBA] Using ROM with good CRC and name tf1_voi0.bin from archive /home/pi/RetroPie/roms/fba/tankfrce4
[libretro INFO] [FBA] Using ROM with good CRC and name tf1_voi1.bin from archive /home/pi/RetroPie/roms/fba/tankfrce4
[libretro INFO] [FBA] Using ROM with good CRC and name tf1_chr8.bin from archive /home/pi/RetroPie/roms/fba/tankfrce4
[libretro INFO] [FBA] Using ROM with good CRC and name tf1_chr0.bin from archive /home/pi/RetroPie/roms/fba/tankfrce4
[libretro INFO] [FBA] Using ROM with good CRC and name tf1_chr1.bin from archive /home/pi/RetroPie/roms/fba/tankfrce4
[libretro INFO] [FBA] Using ROM with good CRC and name tf1_chr2.bin from archive /home/pi/RetroPie/roms/fba/tankfrce4
[libretro INFO] [FBA] Using ROM with good CRC and name tf1_chr3.bin from archive /home/pi/RetroPie/roms/fba/tankfrce4
[libretro INFO] [FBA] Using ROM with good CRC and name tf1_chr4.bin from archive /home/pi/RetroPie/roms/fba/tankfrce4
[libretro INFO] [FBA] Using ROM with good CRC and name tf1_chr5.bin from archive /home/pi/RetroPie/roms/fba/tankfrce4
[libretro INFO] [FBA] Using ROM with good CRC and name tf1_obj0.bin from archive /home/pi/RetroPie/roms/fba/tankfrce4
[libretro INFO] [FBA] Using ROM with good CRC and name tf1_obj1.bin from archive /home/pi/RetroPie/roms/fba/tankfrce4
[INFO] Environ SET_VARIABLES.
[INFO] Saved core options file to "/opt/retropie/configs/all/retroarch-core-options.cfg"
[INFO] Environ GET_VARIABLE fba-cpu-speed-adjust:
[INFO] 	100
[INFO] Environ GET_VARIABLE fba-aspect:
[INFO] 	DAR
[INFO] Environ GET_VARIABLE fba-allow-depth-32:
[INFO] 	disabled
[INFO] Environ GET_VARIABLE fba-vertical-mode:
[INFO] 	disabled
[INFO] Environ GET_VARIABLE fba-frameskip:
[INFO] 	0
[INFO] Environ GET_VARIABLE fba-hiscores:
[INFO] 	enabled
[INFO] Environ GET_VARIABLE fba-samplerate:
[INFO] 	48000
[INFO] Environ GET_VARIABLE fba-sample-interpolation:
[INFO] 	4-point 3rd order
[INFO] Environ GET_VARIABLE fba-fm-interpolation:
[INFO] 	4-point 3rd order
[INFO] Environ GET_VARIABLE fba-analog-speed:
[INFO] 	10
[INFO] Environ GET_VARIABLE fba-cyclone:
[INFO] 	disabled
[INFO] Environ SET_INPUT_DESCRIPTORS:
[INFO] 	RetroPad, User 1, Button "B (bottom)" => "Button 1"
[INFO] 	RetroPad, User 1, Button "Select" => "Coin"
[INFO] 	RetroPad, User 1, Button "D-Pad Up" => "Up"
[INFO] 	RetroPad, User 1, Button "D-Pad Down" => "Down"
[INFO] 	RetroPad, User 1, Button "D-Pad Left" => "Left"
[INFO] 	RetroPad, User 1, Button "D-Pad Right" => "Right"
[INFO] 	RetroPad, User 2, Button "B (bottom)" => "Button 1"
[INFO] 	RetroPad, User 2, Button "Select" => "Coin"
[INFO] 	RetroPad, User 2, Button "D-Pad Up" => "Up"
[INFO] 	RetroPad, User 2, Button "D-Pad Down" => "Down"
[INFO] 	RetroPad, User 2, Button "D-Pad Left" => "Left"
[INFO] 	RetroPad, User 2, Button "D-Pad Right" => "Right"
[INFO] 	RetroPad, User 3, Button "B (bottom)" => "Button 1"
[INFO] 	RetroPad, User 3, Button "Select" => "Coin"
[INFO] 	RetroPad, User 3, Button "D-Pad Up" => "Up"
[INFO] 	RetroPad, User 3, Button "D-Pad Down" => "Down"
[INFO] 	RetroPad, User 3, Button "D-Pad Left" => "Left"
[INFO] 	RetroPad, User 3, Button "D-Pad Right" => "Right"
[INFO] 	RetroPad, User 4, Button "B (bottom)" => "Button 1"
[INFO] 	RetroPad, User 4, Button "Select" => "Coin"
[INFO] 	RetroPad, User 4, Button "D-Pad Up" => "Up"
[INFO] 	RetroPad, User 4, Button "D-Pad Down" => "Down"
[INFO] 	RetroPad, User 4, Button "D-Pad Left" => "Left"
[INFO] 	RetroPad, User 4, Button "D-Pad Right" => "Right"
[libretro INFO] Initialize DIP switches.
[libretro INFO] 'Service Mode' (2)
[libretro INFO]    '(Default) Off'
[libretro INFO]    'Off'
[libretro INFO]    'On'
[INFO] Environ SET_VARIABLES.
[INFO] Saved core options file to "/opt/retropie/configs/all/retroarch-core-options.cfg"
[INFO] Environ GET_VARIABLE fba-dipswitch-tankfrce4-Service_Mode:
[INFO] 	(Default) Off
[libretro INFO] [Cheevos] System RAM set to 0x6e31180c 104624
/opt/retropie/supplementary/runcommand/runcommand.sh: line 1012:  4398 Aborted                 /opt/retropie/emulators/retroarch/bin/retroarch -L /opt/retropie/libretrocores/lr-fbalpha/fbalpha_libretro.so --config /opt/retropie/configs/fba/retroarch.cfg "/home/pi/RetroPie/roms/fba/tankfrce4.zip" --verbose --appendconfig /dev/shm/retroarch.cfg
```

**Comment by dinkc64** [comment]
@Wilstorm Ahh yes, Arcadez is a good friend :)
Here's the nitedriver sample pack: https://www.sendspace.com/file/uy78gk
PM me on the fbalpha forums if you'd like to talk about other files :)
best regards,
- dink

**Comment by Wilstorm** [comment]
@dinkc64 - Thanks a bunch for the samples. That one has been a thorn I've tried to find more than once. Arcadez is a good guy that I do appreciate. He always gives you credit for the games you help getting added to the Plus core. When he posts information and links he throws in a bit of history about the games and useful links. He makes it fun as it should be. It's easy to loose the whole "this is supposed to be fun" concept some days. :)

Thanks again and have a great weekend. Heading out as we have some nice weather here this afternoon.

**Comment by barbudreadmon** [comment]
@dinkc64 i reproduced the crash by launching the game a second time, here is the trace : 
```
=================================================================
==21013==ERROR: AddressSanitizer: heap-buffer-overflow on address 0x62f00000cdc0 at pc 0x7efc36a1feea bp 0x7ffd6f47dba0 sp 0x7ffd6f47db90
WRITE of size 8 at 0x62f00000cdc0 thread T0
    #0 0x7efc36a1fee9 in M6800MapMemory(unsigned char*, unsigned short, unsigned short, int) src/cpu/m6800_intf.cpp:502
    #1 0x7efc35ef9df5 in mcu_bankswitch src/burn/drv/pre90s/d_namcos1.cpp:1180
    #2 0x7efc35f036de in DrvScan src/burn/drv/pre90s/d_namcos1.cpp:2114
    #3 0x7efc3544cf79 in BurnAreaScan src/burn/burn.cpp:871
    #4 0x7efc353d6e37 in BurnStateDecompress(unsigned char*, int, int) src/burner/statec.cpp:165
    #5 0x7efc36c66e1d in BurnStateLoadEmbed(RFILE*, int, int, int (*)()) src/burner/libretro/libretro.cpp:1566
    #6 0x7efc36c671b7 in BurnStateLoad(char*, int, int (*)()) src/burner/libretro/libretro.cpp:1595
    #7 0x7efc36c6d927 in retro_load_game_common src/burner/libretro/libretro.cpp:1257
    #8 0x7efc36c6e518 in retro_load_game src/burner/libretro/libretro.cpp:1308
    #9 0x562e5c3e6ae8  (/usr/bin/retroarch+0x46ae8)
    #10 0x562e5c401419  (/usr/bin/retroarch+0x61419)
    #11 0x562e5c3f19d4  (/usr/bin/retroarch+0x519d4)
    #12 0x562e5c3ea3d0  (/usr/bin/retroarch+0x4a3d0)
    #13 0x562e5c3fee04  (/usr/bin/retroarch+0x5ee04)
    #14 0x562e5c3ff1db  (/usr/bin/retroarch+0x5f1db)
    #15 0x562e5c3ff903  (/usr/bin/retroarch+0x5f903)
    #16 0x562e5c3e5ae8  (/usr/bin/retroarch+0x45ae8)
    #17 0x7efc54c6bae6 in __libc_start_main (/lib64/libc.so.6+0x21ae6)
    #18 0x562e5c3e2a49  (/usr/bin/retroarch+0x42a49)

0x62f00000cdc0 is located 1600 bytes to the right of 50048-byte region [0x62f000000400,0x62f00000c780)
allocated by thread T0 here:
    #0 0x7efc5a98bda0 in __interceptor_malloc /var/tmp/portage/sys-devel/gcc-8.2.0-r6/work/gcc-8.2.0/libsanitizer/asan/asan_malloc_linux.cc:86
    #1 0x7efc36a2c6fa in M6809Init(int) src/cpu/m6809_intf.cpp:109

SUMMARY: AddressSanitizer: heap-buffer-overflow src/cpu/m6800_intf.cpp:502 in M6800MapMemory(unsigned char*, unsigned short, unsigned short, int)
Shadow bytes around the buggy address:
  0x0c5e7fff9960: fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa
  0x0c5e7fff9970: fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa
  0x0c5e7fff9980: fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa
  0x0c5e7fff9990: fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa
  0x0c5e7fff99a0: fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa
=>0x0c5e7fff99b0: fa fa fa fa fa fa fa fa[fa]fa fa fa fa fa fa fa
  0x0c5e7fff99c0: fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa
  0x0c5e7fff99d0: fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa
  0x0c5e7fff99e0: fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa
  0x0c5e7fff99f0: fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa
  0x0c5e7fff9a00: fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa
Shadow byte legend (one shadow byte represents 8 application bytes):
  Addressable:           00
  Partially addressable: 01 02 03 04 05 06 07 
  Heap left redzone:       fa
  Freed heap region:       fd
  Stack left redzone:      f1
  Stack mid redzone:       f2
  Stack right redzone:     f3
  Stack after return:      f5
  Stack use after scope:   f8
  Global redzone:          f9
  Global init order:       f6
  Poisoned by user:        f7
  Container overflow:      fc
  Array cookie:            ac
  Intra object redzone:    bb
  ASan internal:           fe
  Left alloca redzone:     ca
  Right alloca redzone:    cb
==21013==ABORTING
```

This is from loading the minimal savestate used to store board settings, we are simply running `BurnStateSave(g_autofs_path, 0);` at exit and `BurnStateLoad(g_autofs_path, 0, NULL);`, i think standalone is doing something similar ?

**Comment by dinkc64** [comment]
@barbudreadmon  OOPS :)  fix is in.

@Wilstorm that's nice, I agree, keep it fun :)  The weather is getting nicer here as well, I keep thinking - better enjoy it before it gets too hot.  hehe.. :)

**Comment by Wilstorm** [comment]
@barbudreadmon - Thanks for verifying the bug.

@dinkc64 - Thanks for the fix. I agree it will get hot all to soon. Then we can complain it's to hot. :) We get pretty humid here during the summer months also. Right now we are dealing with a lot of flooding but we are supposed to crest about 18 feel above flood stage tonight into tomorrow, then things should settle in for spring/summer.

Should I leave this open or go ahead and close it until a fix is verified?

**Comment by barbudreadmon** [comment]
@Wilstorm the fix has been merged 2 days ago, i was waiting for your confirmation before closing the issue.

**Comment by Wilstorm** [comment]
@barbudreadmon - Ah ok, I will test it right now.

**Comment by Wilstorm** [comment]
@barbudreadmon @dinkc64 - Thanks good sirs, it works flawless. I had no idea they had a 4 player version (I was using the 2 player for the longest time) which is well...finger snapping groovy! ;)
