### ISSUE TITLE
Dark Seal savestates are not working

### ISSUE THREAD

**Issue by furiadeoso** [libretro/fbalpha#73]
Hi!

When savestate function is used in DARKSEAL retroarch crashes and closes.
Obviously, netplay does not work either.

Regards.

**Comment by barbudreadmon** [comment]
I can reproduce this, here is the trace : 
```
==31925==The signal is caused by a READ memory access.
==31925==Hint: address points to the zero page.
#0 0x7f4f36f5faa6 in memcpy (/lib64/libc.so.6+0xa8aa6)
#1 0x7f4f3cbda7be  (/usr/lib/gcc/x86_64-pc-linux-gnu/7.3.0/libasan.so+0x797be)
#2 0x7f4f1d85b436 in memcpy /usr/include/bits/string_fortified.h:34
#3 0x7f4f1d85b436 in burn_write_state_cb src/burner/libretro/libretro.cpp:967
#4 0x7f4f1c4ad904 in deco16Scan() src/burn/drv/dataeast/deco16ic.cpp:860
#5 0x7f4f1c5209b5 in DrvScan src/burn/drv/dataeast/d_darkseal.cpp:710
#6 0x7f4f1c08afb9 in BurnAreaScan src/burn/burn.cpp:871
#7 0x7f4f1d85c765 in retro_serialize src/burner/libretro/libretro.cpp:1022
#8 0x55b8ebd3c893  (/usr/bin/retroarch+0x63893)
#9 0x55b8ebd27c44  (/usr/bin/retroarch+0x4ec44)
#10 0x55b8ebd291a2  (/usr/bin/retroarch+0x501a2)
#11 0x55b8ebec1dbf  (/usr/bin/retroarch+0x1e8dbf)
#12 0x55b8ebebd89d  (/usr/bin/retroarch+0x1e489d)
#13 0x55b8ebef9dfa  (/usr/bin/retroarch+0x220dfa)
#14 0x55b8ebea373e  (/usr/bin/retroarch+0x1ca73e)
#15 0x55b8ebd21355  (/usr/bin/retroarch+0x48355)
#16 0x55b8ebd25871  (/usr/bin/retroarch+0x4c871)
#17 0x55b8ebd1ee3f  (/usr/bin/retroarch+0x45e3f)
#18 0x7f4f36ed8ae6 in __libc_start_main (/lib64/libc.so.6+0x21ae6)
#19 0x55b8ebd1ba09  (/usr/bin/retroarch+0x42a09)
```
Commenting out those lines fix the crash :  https://github.com/libretro/fbalpha/blob/1769aab9902645ded8b102c4eeaa15ac8cced687/src/burn/drv/dataeast/deco16ic.cpp#L856-L866 

Maybe @dinkc64 can help ?

**Comment by dinkc64** [comment]
sorry about that!  fix is on main git.

**Comment by barbudreadmon** [comment]
Thanks, merged :)

**Comment by furiadeoso** [comment]
Thanks!
