### ISSUE TITLE
Shinobi (set 6, System 16A, unprotected)

### ISSUE THREAD

**Issue by gegecom83** [libretro/fbalpha#92]
Hello
I am on mac osx and I can not play Shinobi (set 6, System 16A, unprotected) "shinobi.zip" the game that launches and after 10 seconds it stops with an error:
Segmentation fault: 11
but with "shinobi6.zip" works fine.
Thank you for your help
[My log.txt](https://github.com/libretro/fbalpha/files/2753003/My.log.txt)

**Comment by barbudreadmon** [comment]
Confirming the issue on my side, here is the trace : 
```
==6872==ERROR: AddressSanitizer: SEGV on unknown address 0x000000000008 (pc 0x7fe21cfa3695 bp 0x0c6000001dcd sp 0x7ffc09645db0 T0)
==6872==The signal is caused by a WRITE memory access.
==6872==Hint: address points to the zero page.
    #0 0x7fe21cfa3694 in push src/cpu/i8039/i8039.cpp:272
    #1 0x7fe21cfa3694 in Ext_IRQ src/cpu/i8039/i8039.cpp:687
    #2 0x7fe21cfa957e in I8039SetIrqState(int) src/cpu/i8039/i8039.cpp:1044
    #3 0x7fe21cb79f69 in System16N7751ControlWrite(unsigned int, unsigned int) src/burn/drv/sega/sys16_run.cpp:825
    #4 0x7fe21b701224 in YM2151WriteReg src/burn/snd/ym2151.c:1214
    #5 0x7fe21cb794b3 in BurnYM2151WriteRegister src/burn/snd/burn_ym2151.h:52
    #6 0x7fe21cb794b3 in System16Z80PortWrite(unsigned short, unsigned char) src/burn/drv/sega/sys16_run.cpp:512
    #7 0x7fe21cf10203 in ZetWriteIO(unsigned int, unsigned char) src/cpu/z80_intf.cpp:65
    #8 0x7fe21d117ebe in op_d3 src/cpu/z80/z80.cpp:3281
    #9 0x7fe21d11d3ad in Z80Execute(int) src/cpu/z80/z80.cpp:3598
    #10 0x7fe21cf10f7b in ZetRun(int) src/cpu/z80_intf.cpp:397
    #11 0x7fe21cb86287 in System16AFrame() src/burn/drv/sega/sys16_run.cpp:2759
    #12 0x7fe21b97daa5 in BurnDrvFrame src/burn/burn.cpp:740
    #13 0x7fe21d14d416 in ForceFrameStep src/burner/libretro/libretro.cpp:488
    #14 0x7fe21d14f7c1 in retro_run src/burner/libretro/libretro.cpp:892
    #15 0x561eb3d15b5f  (/usr/bin/retroarch+0x46b5f)
    #16 0x561eb3d1afcd  (/usr/bin/retroarch+0x4bfcd)
    #17 0x561eb3d1491f  (/usr/bin/retroarch+0x4591f)
    #18 0x7fe23697aae6 in __libc_start_main (/lib64/libc.so.6+0x21ae6)
    #19 0x561eb3d11859  (/usr/bin/retroarch+0x42859)

AddressSanitizer can not provide additional info.
SUMMARY: AddressSanitizer: SEGV src/cpu/i8039/i8039.cpp:272 in push
==6872==ABORTING
```

**Comment by gegecom83** [comment]
Thank you for your quick reply

**Comment by dinkc64** [comment]
I can't make this crash in standalone :/  hrmmm

**Comment by gegecom83** [comment]
dinkc64 Thank you
